### ISSUE TITLE
libclang.dll dependency

### ISSUE THREAD

**Issue by myth987** [jgonzalezdr/CppUMockGen#8]
libclang.dll is missing from the zipped / install packages, thus making those unusable if no libclang is already installed in the host.

Could the executable file be statically linked or libclang.dll distributed with the executable file?

**Comment by jgonzalezdr** [comment]
Good point, I'll try to fix this ASAP.

**Comment by jgonzalezdr** [comment]
Fixed in #15. A bit late btw...
